name: Coding Standards Check
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: 3.7
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 mypy pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint With flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Type Hint Check With mypy
        run: |
          # stop the build if there are missing type hints
          mypy --exclude build --install-types --non-interactive --ignore-missing-imports --strict .
      - name: Test With pytest
        run: |
          pytest
